V6 improvements
configcat/java-sdk pull request #45
Opened 2024-03-27 10:44 UTC by novalisdenahi

### Describe the purpose of your pull request

- Rename `SettingsValue` to correct `SettingValue`
- Fix hashed starts/ends with comparator trimming
- `userAttributeToString `method handles `Float`
- Fix `getKeyAndValue` missing exception
- Improve prerequisite flag evaluation type checks
- Typo fix

### Requirement checklist (only if applicable)

- [ ] I have covered the applied changes with automated tests.
- [ ] I have executed the full automated test set against my changes.
- [ ] I have validated my changes against all supported platform versions.
- [ ] I have read and accepted the [contribution agreement](https://github.com/configcat/legal/blob/main/contribution-agreement.md).

2024-03-27 15:53 UTC, adams85 requested changes
All good, thanks for making this adjustments!

On top of these, could you add this minor consistency improvement as well: https://github.com/configcat/.net-sdk/pull/89/commits/4692622a4cb54fce272b3689f6d13dee3be8e96b ?

Plus, these few extra test cases: https://github.com/configcat/.net-sdk/pull/89/commits/98042c1c383a2c4d835de6011591c7b884786e39

2024-03-28 07:50 UTC, adams85 commented on src/main/java/com/configcat/RolloutEvaluator.java
> +        validateSettingValueType(evaluateResult.value, prerequsiteFlagSetting.getType());
typo
```suggestion
        validateSettingValueType(evaluateResult.value, prerequisiteFlagSetting.getType());
```

2024-03-28 07:51 UTC, adams85 approved these changes

2024-03-28 12:35 UTC, z4kn4fein approved these changes

2024-04-03 14:12 UTC, merged